{{- if not .Values.flask.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wish-journal.fullname" . }}-secret
  labels:
    {{- include "wish-journal.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.flask.secretKey | default (randAlphaNum 32) | b64enc | quote }}
{{- end }}
